name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    environment: Prod
    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        #env:
         # THE_EJEMPLO: ${{ secrets.Ejemplo }}
        run: |
          echo "::add-mask::#es,${{ secrets.Entorno }}"
          THE_EJEMPLO="::add-mask::#es,${{ secrets.Entorno }}"
          echo "The GitHub Action Secret will be masked:  "
          #echo SECRET=THE_EJEMPLO >> $GITHUB_ENV
          #echo SECRET="::add-mask::#es,${{ secrets.Entorno }}" >> $GITHUB_ENV
      - name: Step 2 - Check environment variables
        run: |
          echo $SECRET

