name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        env:
          THE_EJEMPLO: ${{ secrets.Ejemplo }}
        run: |
          echo "The GitHub Action Secret will be masked:  "
          #echo $THE_EJEMPLO >> $GITHUB_ENV

